// Package firewall builds and applies the nftables rules managed by VegaSyncor and
// lists the open ports and connections of the server.
//
// VegaSyncor uses its own table ("inet vegasyncor") and never touches other rules.
// With nftables a packet must be accepted by every table, so this table can only
// add restrictions: removing it restores the system as it was.
package firewall

import (
	"fmt"
	"strings"

	"vegasyncor/internal/config"
)

const Table = "vegasyncor"

// Kinds of rules (the TUI shows a translated description for each).
const (
	KindLoopback    = "loopback"
	KindEstablished = "established"
	KindInvalid     = "invalid"
	KindSSH         = "ssh"
	KindPing        = "ping"
	KindICMPv6      = "icmpv6"
	KindDHCP        = "dhcp"
	KindDNS         = "dns"
	KindNTP         = "ntp"
	KindWeb         = "web"
	KindSMB         = "smb"
	KindUser        = "user"
	KindDrop        = "drop"
)

// Rule is one line (or group of lines) of the firewall, as applied and as shown.
type Rule struct {
	ID        string   `json:"id"`        // used as nftables comment "vs:<id>" to read counters
	Kind      string   `json:"kind"`      // Kind* constants
	Builtin   bool     `json:"builtin"`   // generated by the preset (not editable)
	Direction string   `json:"direction"` // config.FwIn | config.FwOut
	Action    string   `json:"action"`    // config.FwAllow | config.FwBlock
	Proto     string   `json:"proto"`     // config.FwTCP | FwUDP | FwAny ("" for special rules)
	Ports     []string `json:"ports,omitempty"`
	Hosts     []string `json:"hosts,omitempty"` // remote hosts/networks; empty = any
	Comment   string   `json:"comment,omitempty"`
	Packets   uint64   `json:"packets"` // filled from the nftables counters
	Bytes     uint64   `json:"bytes"`
}

// Plan returns the rules of the lockdown preset for f. smbHosts are the IP
// addresses of the hosts in the connections (resolved by the caller).
func Plan(f config.Firewall, smbHosts []string) []Rule {
	var in, out []Rule
	b := func(id, kind, dir, action, proto string, ports, hosts []string) Rule {
		return Rule{ID: id, Kind: kind, Builtin: true, Direction: dir, Action: action, Proto: proto, Ports: ports, Hosts: hosts}
	}
	user := func(dir, action string) []Rule {
		var out []Rule
		for _, r := range f.Rules {
			if r.Direction != dir || r.Action != action {
				continue
			}
			ur := Rule{ID: "rule-" + r.ID, Kind: KindUser, Direction: r.Direction, Action: r.Action,
				Proto: r.Proto, Comment: r.Comment}
			if r.Port != "" {
				ur.Ports = []string{r.Port}
			}
			if r.Host != "" {
				ur.Hosts = []string{r.Host}
			}
			out = append(out, ur)
		}
		return out
	}

	// incoming
	in = append(in,
		b("in-lo", KindLoopback, config.FwIn, config.FwAllow, "", nil, nil),
		b("in-est", KindEstablished, config.FwIn, config.FwAllow, "", nil, nil),
		b("in-inv", KindInvalid, config.FwIn, config.FwBlock, "", nil, nil),
	)
	in = append(in, user(config.FwIn, config.FwBlock)...)
	in = append(in, b("in-ssh", KindSSH, config.FwIn, config.FwAllow, config.FwTCP,
		[]string{fmt.Sprint(f.SSH())}, f.AdminHosts))
	if f.AllowPing {
		in = append(in, b("in-ping", KindPing, config.FwIn, config.FwAllow, "", nil, nil))
	}
	in = append(in,
		b("in-icmp6", KindICMPv6, config.FwIn, config.FwAllow, "", nil, nil),
		b("in-dhcp", KindDHCP, config.FwIn, config.FwAllow, config.FwUDP, []string{"68"}, nil),
	)
	in = append(in, user(config.FwIn, config.FwAllow)...)
	in = append(in, b("in-drop", KindDrop, config.FwIn, config.FwBlock, "", nil, nil))

	// outgoing
	out = append(out,
		b("out-lo", KindLoopback, config.FwOut, config.FwAllow, "", nil, nil),
		b("out-est", KindEstablished, config.FwOut, config.FwAllow, "", nil, nil),
		b("out-inv", KindInvalid, config.FwOut, config.FwBlock, "", nil, nil),
	)
	out = append(out, user(config.FwOut, config.FwBlock)...)
	out = append(out,
		b("out-dns", KindDNS, config.FwOut, config.FwAllow, config.FwAny, []string{"53"}, nil),
		b("out-ntp", KindNTP, config.FwOut, config.FwAllow, config.FwUDP, []string{"123"}, nil),
		b("out-dhcp", KindDHCP, config.FwOut, config.FwAllow, config.FwUDP, []string{"67"}, nil),
		b("out-ping", KindPing, config.FwOut, config.FwAllow, "", nil, nil),
		b("out-icmp6", KindICMPv6, config.FwOut, config.FwAllow, "", nil, nil),
	)
	if f.AllowWeb {
		out = append(out, b("out-web", KindWeb, config.FwOut, config.FwAllow, config.FwTCP, []string{"80", "443"}, nil))
	}
	if len(smbHosts) > 0 {
		out = append(out, b("out-smb", KindSMB, config.FwOut, config.FwAllow, config.FwTCP, []string{"139", "445"}, smbHosts))
	}
	out = append(out, user(config.FwOut, config.FwAllow)...)
	out = append(out, b("out-drop", KindDrop, config.FwOut, config.FwBlock, "", nil, nil))
	return append(in, out...)
}

// Script returns the nftables script that replaces the VegaSyncor table with rules.
// The "table / delete table" prefix makes the replacement atomic and also works
// when the table does not exist yet.
func Script(rules []Rule) string {
	var b strings.Builder
	fmt.Fprintf(&b, "table inet %s\ndelete table inet %s\ntable inet %s {\n", Table, Table, Table)
	for _, chain := range []struct{ name, hook, dir string }{
		{"input", "input", config.FwIn}, {"output", "output", config.FwOut},
	} {
		fmt.Fprintf(&b, "\tchain %s {\n\t\ttype filter hook %s priority filter; policy drop;\n", chain.name, chain.hook)
		for _, r := range rules {
			if r.Direction != chain.dir {
				continue
			}
			for _, l := range ruleLines(r) {
				b.WriteString("\t\t" + l + "\n")
			}
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// DisableScript removes the VegaSyncor table (works also if it does not exist).
func DisableScript() string {
	return fmt.Sprintf("table inet %s\ndelete table inet %s\n", Table, Table)
}

func ruleLines(r Rule) []string {
	tail := fmt.Sprintf(`counter %s comment "vs:%s"`, verdict(r.Action), r.ID)
	in := r.Direction == config.FwIn
	switch r.Kind {
	case KindLoopback:
		if in {
			return []string{`iif "lo" ` + tail}
		}
		return []string{`oif "lo" ` + tail}
	case KindEstablished:
		return []string{"ct state established,related " + tail}
	case KindInvalid:
		return []string{"ct state invalid " + tail}
	case KindPing:
		return []string{"icmp type echo-request " + tail, "icmpv6 type echo-request " + tail}
	case KindICMPv6:
		return []string{"icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, " +
			"nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } " + tail}
	case KindDrop:
		prefix := "vegasyncor-out-drop: "
		if in {
			prefix = "vegasyncor-in-drop: "
		}
		return []string{fmt.Sprintf(`limit rate 10/minute burst 5 packets log prefix "%s" level info`, prefix), tail}
	}

	// rules on hosts and ports
	match := portMatch(r.Proto, r.Ports)
	if len(r.Hosts) == 0 {
		return []string{strings.TrimSpace(match + " " + tail)}
	}
	var v4, v6 []string
	for _, h := range compactHosts(r.Hosts) {
		if config.IsIPv6Spec(h) {
			v6 = append(v6, h)
		} else {
			v4 = append(v4, h)
		}
	}
	dir := "saddr"
	if !in {
		dir = "daddr"
	}
	var lines []string
	for _, g := range []struct {
		fam   string
		hosts []string
	}{{"ip", v4}, {"ip6", v6}} {
		if len(g.hosts) > 0 {
			parts := []string{g.fam, dir, set(g.hosts), match, tail}
			lines = append(lines, strings.Join(nonEmpty(parts), " "))
		}
	}
	return lines
}

func portMatch(proto string, ports []string) string {
	if len(ports) == 0 {
		switch proto {
		case config.FwTCP:
			return "meta l4proto tcp"
		case config.FwUDP:
			return "meta l4proto udp"
		}
		return ""
	}
	switch proto {
	case config.FwTCP:
		return "tcp dport " + set(ports)
	case config.FwUDP:
		return "udp dport " + set(ports)
	}
	return "meta l4proto { tcp, udp } th dport " + set(ports)
}

func set(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func verdict(action string) string {
	if action == config.FwBlock {
		return "drop"
	}
	return "accept"
}

func nonEmpty(parts []string) []string {
	var out []string
	for _, p := range parts {
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}
